LogReaderJob:
    Db:
        LogsConnString:
            settings-key: LogReaderJob-LogsConnString
            types:
                - AzureTableStorage
        ScanLogsConnString:
            settings-key: LogReaderJob-ScanLogsConnString
            types:
                - JsonArray
    Reader:
        ParseContextAsJson:
            settings-key: ParseContextValue
        ElasticTopic:
            settings-key: ElasticTopic
            types:
              - Optional
        ExcludeTables:
            settings-key: ExcludeTablesValue
            types:
                - JsonArray
                - Optional

        LogAggregatorHost:
            settings-key: LogAggregatorHostValue

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

